# Prepare-CosmeticsLab.ps1 — build the CosmeticsLab C1 release package (payload + manifest)
# and optionally generate the private per-user inventories.json fixture.
#
# Usage:
#   pwsh -NoProfile -File scripts\cosmetics-lab\Prepare-CosmeticsLab.ps1
#   pwsh -NoProfile -File scripts\cosmetics-lab\Prepare-CosmeticsLab.ps1 -GenerateFixture -SteamId64 <steamid64>
#
# The private fixture goes to E:\CS2MOD\app-data\cosmetics-lab\inventory-simulator\inventories.json
# and is NEVER included in the release payload or the shareable ZIP.

param(
    [switch]$GenerateFixture,
    [string]$SteamId64 = '',
    [string]$ReleaseRoot = ''
)

. (Join-Path $PSScriptRoot 'CosmeticsLab.Common.ps1')

$wtRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$lockPath = Join-Path $wtRoot 'runtime\inventory-simulator.lock.json'
$presetPath = Join-Path $wtRoot 'experiments\cosmetics-lab\inventory-simulator\test-preset.json'
$manualTestPath = Join-Path $wtRoot 'experiments\cosmetics-lab\inventory-simulator\MANUAL-TEST.md'
$downloadDir = Join-Path $wtRoot 'temp\cosmetics-lab\downloads'
if (-not $ReleaseRoot) { $ReleaseRoot = Join-Path $script:Cs2ModRoot 'releases\cosmetics-lab' }

$lock = Read-C1Json -Path $lockPath
if ($lock.status -ne 'candidate') { throw "Lock status is '$($lock.status)', expected 'candidate' for C1." }

Write-C1Step 'Verifying / fetching pinned upstream assets'
$assets = @(
    @{
        name  = 'inventory-simulator'; asset = $lock.artifact.asset
        url   = $lock.artifact.url;    sha256 = $lock.artifact.sha256
    },
    @{
        name  = 'counterstrikesharp'; asset = (Split-Path $lock.framework.counterstrikesharp.url -Leaf)
        url   = $lock.framework.counterstrikesharp.url; sha256 = $lock.framework.counterstrikesharp.sha256
    },
    @{
        name  = 'metamod'; asset = (Split-Path $lock.framework.metamod.url -Leaf)
        url   = $lock.framework.metamod.url; sha256 = $lock.framework.metamod.sha256
    }
)
New-Item -ItemType Directory -Force -Path $downloadDir | Out-Null
foreach ($a in $assets) {
    $local = Join-Path $downloadDir $a.asset
    if (-not (Test-Path -LiteralPath $local -PathType Leaf)) {
        Write-Host "   downloading $($a.url)"
        Invoke-WebRequest -Uri $a.url -OutFile $local
    }
    $actual = Get-C1FileSha256Hex -Path $local
    if ($actual -ne $a.sha256) {
        throw "Asset $($a.asset) hash mismatch`n     expected $($a.sha256)`n     actual   $actual"
    }
    Write-C1Ok "$($a.asset) ($($a.sha256.Substring(0, 16))...)"
}

Write-C1Step 'Unpacking assets to staging'
$staging = Join-Path $wtRoot 'temp\cosmetics-lab\staging'
if (Test-Path -LiteralPath $staging) { Remove-Item -LiteralPath $staging -Recurse -Force }
foreach ($a in $assets) {
    $dest = Join-Path $staging $a.name
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    Expand-Archive -Path (Join-Path $downloadDir $a.asset) -DestinationPath $dest
    Write-C1Ok "$($a.name) -> staging"
}

Write-C1Step 'Assembling release payload (csgo-relative layout)'
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$releaseDir = Join-Path $ReleaseRoot "inventory-simulator-c1-$timestamp"
$payloadDir = Join-Path $releaseDir 'payload'
New-Item -ItemType Directory -Force -Path $payloadDir | Out-Null

# role per source: framework | inventory-simulator; project-config files are generated below.
$sourceRoles = @{
    'counterstrikesharp' = 'framework'
    'metamod'            = 'framework'
    'inventory-simulator' = 'inventory-simulator'
}
$payloadEntries = New-Object System.Collections.Generic.List[object]
$seen = @{}
foreach ($a in $assets) {
    $srcRoot = Join-Path $staging $a.name
    $files = Get-ChildItem -LiteralPath $srcRoot -Recurse -File -Force
    foreach ($f in $files) {
        $rel = $f.FullName.Substring($srcRoot.Length).TrimStart('\').Replace('\', '/')
        if ($seen.ContainsKey($rel)) { throw "Duplicate payload path from two sources: $rel" }
        $seen[$rel] = $true
        $dest = Join-Path $payloadDir ($rel -replace '/', '\')
        $destParent = Split-Path $dest -Parent
        if (-not (Test-Path -LiteralPath $destParent)) { New-Item -ItemType Directory -Force -Path $destParent | Out-Null }
        Copy-Item -LiteralPath $f.FullName -Destination $dest
        $payloadEntries.Add([pscustomobject]@{ path = $rel; role = $sourceRoles[$a.name] })
    }
}

Write-C1Step 'Generating C1 project-config files'
$c1Cfg = @"
// CosmeticsLab C1 experiment-owned launch config (executed via +exec cosmeticslab_c1).
// Keeps the runtime local-only: dummy API endpoint + every public-API path disabled.
// Generated by Prepare-CosmeticsLab.ps1; do not hand-edit.
invsim_url "http://127.0.0.1:9"
invsim_apikey ""
invsim_ws_enabled 0
invsim_wslogin 0
invsim_public_api_stattrak_increment 0
invsim_public_api_spray_consume 0
invsim_spray_enabled 0
invsim_spray_on_use 0
invsim_spraychanger_enabled 0
invsim_require_inventory 0
invsim_fallback_team 0
invsim_minmodels 1
invsim_persist_inventory 0
echo "[CosmeticsLab-C1] experiment convars applied"
"@
$cfgRel = "cfg/$script:C1CfgName"
$cfgDest = Join-Path $payloadDir ($cfgRel -replace '/', '\')
New-Item -ItemType Directory -Force -Path (Split-Path $cfgDest -Parent) | Out-Null
[System.IO.File]::WriteAllText($cfgDest, $c1Cfg.Replace("`n", "`r`n"), [System.Text.UTF8Encoding]::new($false))
$payloadEntries.Add([pscustomobject]@{ path = $cfgRel; role = 'project-config' })

$coreJson = @{
    FollowCS2ServerGuidelines = $false
} | ConvertTo-Json
$coreRel = 'addons/counterstrikesharp/configs/core.json'
$coreDest = Join-Path $payloadDir ($coreRel -replace '/', '\')
New-Item -ItemType Directory -Force -Path (Split-Path $coreDest -Parent) | Out-Null
[System.IO.File]::WriteAllText($coreDest, $coreJson + "`r`n", [System.Text.UTF8Encoding]::new($false))
$payloadEntries.Add([pscustomobject]@{ path = $coreRel; role = 'project-config' })
Write-C1Ok "cfg/$script:C1CfgName + addons/counterstrikesharp/configs/core.json (FollowCS2ServerGuidelines=false)"

Write-C1Step 'Building manifest'
$payload = foreach ($e in $payloadEntries) {
    $full = Join-Path $payloadDir ($e.path -replace '/', '\')
    [pscustomobject]@{
        path   = $e.path
        role   = $e.role
        sha256 = Get-C1FileSha256Hex -Path $full
    }
}
$steamInf = $null
try {
    $csRoot = Find-C1Cs2Root
    $infLines = Get-Content -LiteralPath (Join-Path $csRoot 'game\csgo\steam.inf')
    $patchVersion = ($infLines | Where-Object { $_ -match '^PatchVersion=' }) -replace '^PatchVersion=', ''
    $clientVersion = ($infLines | Where-Object { $_ -match '^ClientVersion=' }) -replace '^ClientVersion=', ''
    $acfPath = Join-Path $csRoot '..\..\appmanifest_730.acf'
    $buildId = ''
    if (Test-Path -LiteralPath $acfPath) {
        $buildId = [regex]::Match((Get-Content -LiteralPath $acfPath -Raw), '"buildid"\s+"(\d+)"').Groups[1].Value
    }
    $steamInf = [pscustomobject]@{ patchVersion = $patchVersion; clientVersion = $clientVersion; buildId = $buildId }
} catch {
    Write-Host "   WARN: could not read live CS2 build for manifest ($($_.Exception.Message))"
}
$manifest = [pscustomobject]@{
    kind        = 'cosmetics-lab-c1-release'
    schemaVersion = 1
    createdAt   = (Get-Date -Format 'o')
    experiment  = 'inventory-simulator-c1'
    lock        = [pscustomobject]@{
        repository = $lock.repository; tag = $lock.tag; ref = $lock.ref
        status     = $lock.status
    }
    components  = [pscustomobject]@{
        'inventory-simulator' = [pscustomobject]@{
            tag = $lock.tag; ref = $lock.ref; url = $lock.artifact.url; assetSha256 = $lock.artifact.sha256
        }
        counterstrikesharp = [pscustomobject]@{
            version = $lock.framework.counterstrikesharp.version
            ref     = $lock.framework.counterstrikesharp.ref
            url     = $lock.framework.counterstrikesharp.url
            assetSha256 = $lock.framework.counterstrikesharp.sha256
        }
        metamod = [pscustomobject]@{
            version = $lock.framework.metamod.version
            url     = $lock.framework.metamod.url
            assetSha256 = $lock.framework.metamod.sha256
        }
    }
    observedCs2Build = $steamInf
    payload     = @($payload)
    privateFixture = [pscustomobject]@{
        note          = 'The per-user inventories.json is generated at install time from E:\CS2MOD\app-data\cosmetics-lab\inventory-simulator and must NOT be bundled into this release or any shareable ZIP.'
        installedPath = ($script:C1FixtureInstalledRelPath -replace '\\', '/')
        schema        = 'InventorySimulator EquippedV5 (Dictionary<ulong, EquippedV5Response>), top-level keyed by SteamID64'
    }
    gameinfoModification = [pscustomobject]@{
        file    = 'gameinfo.gi'
        action  = 'insert-only after SearchPaths opening brace'
        line    = $script:C1GameinfoLine
    }
}
$manifestPath = Join-Path $releaseDir 'manifest.json'
$manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $manifestPath -Encoding utf8NoBOM
Write-C1Ok "manifest.json ($($manifest.payload.Count) payload entries)"

Write-C1Step 'Copying experiment docs into release'
Copy-Item -LiteralPath $manualTestPath -Destination (Join-Path $releaseDir 'MANUAL-TEST.md')
$restoreDoc = @"
# Restore instructions (CosmeticsLab C1)

Run from the cosmetics-lab worktree:

```powershell
pwsh -NoProfile -File scripts\cosmetics-lab\Restore-CosmeticsLab.ps1 -BackupDir <backup-dir> -Apply
```

The backup dir is printed by Install-CosmeticsLab.ps1 (under E:\CS2MOD\backups\cosmetics-lab\).

Restore removes only files the C1 install created, restores gameinfo.gi byte-for-byte to its
pre-C1 hash, and verifies the result. Historical logs, metamod user data and unrelated files are
never touched.
"@
[System.IO.File]::WriteAllText((Join-Path $releaseDir 'RESTORE.md'), $restoreDoc.Replace("`n", "`r`n"), [System.Text.UTF8Encoding]::new($false))

Write-C1Step 'Packing shareable ZIP (no private data)'
$zipPath = Join-Path $ReleaseRoot "inventory-simulator-c1-$timestamp.zip"
if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
Compress-Archive -Path (Join-Path $releaseDir 'payload'), $manifestPath, (Join-Path $releaseDir 'MANUAL-TEST.md'), (Join-Path $releaseDir 'RESTORE.md') -DestinationPath $zipPath
Write-C1Ok $zipPath

Write-C1Step 'Private fixture'
if ($GenerateFixture) {
    if ($SteamId64 -notmatch '^\d{17}$') { throw "-SteamId64 must be a 17-digit SteamID64 (got '$SteamId64')." }
    $preset = Read-C1Json -Path $presetPath
    # Strip private-repo-only annotation keys (prefixed with _) so the runtime file
    # matches the upstream EquippedV5 schema exactly.
    function Remove-AnnotationKeys($obj) {
        if ($obj -is [System.Management.Automation.PSCustomObject]) {
            $clean = [ordered]@{}
            foreach ($p in $obj.PSObject.Properties) {
                if ($p.Name.StartsWith('_')) { continue }
                $clean[$p.Name] = Remove-AnnotationKeys $p.Value
            }
            return [pscustomobject]$clean
        }
        if ($obj -is [System.Collections.IEnumerable] -and $obj -isnot [string] -and $obj -isnot [pscustomobject]) {
            return @($obj | ForEach-Object { Remove-AnnotationKeys $_ })
        }
        return $obj
    }
    $player = Remove-AnnotationKeys $preset.player
    $fixture = [ordered]@{}; $fixture[$SteamId64] = $player
    $fixtureJson = $fixture | ConvertTo-Json -Depth 12
    $appDataDir = Join-Path $script:Cs2ModRoot 'app-data\cosmetics-lab\inventory-simulator'
    New-Item -ItemType Directory -Force -Path $appDataDir | Out-Null
    $fixturePath = Join-Path $appDataDir 'inventories.json'
    [System.IO.File]::WriteAllText($fixturePath, $fixtureJson + "`r`n", [System.Text.UTF8Encoding]::new($false))
    Write-C1Ok "private fixture written: $fixturePath (SteamID64 kept out of Git/release)"
} else {
    Write-Host "   skipped (pass -GenerateFixture -SteamId64 <id> to generate)"
}

Write-Host ''
Write-C1Ok "release directory: $releaseDir"
Write-C1Ok "manifest:          $manifestPath"
